apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-template.yaml
  - network-policy-template.yaml
  - resource-quota.yaml
  - envoy-sidecar-configmap.yaml
  - opa-policy-configmap.yaml
  - tenant-minio.yaml
  - tenant-postgres.yaml
  - tenant-mongodb.yaml
  - tenant-keycloak.yaml
  - tenant-openbao.yaml
