apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tenant-isolation-policy
  namespace: drr-tnt-base-template
spec:
  endpointSelector: {}
  ingress:
    # Allow traffic within the same tenant environment
    - fromEndpoints:
        - matchLabels:
            darueira.io/tier: tenant-workload
    # Allow traffic from API Gateway DataPlane strictly to Envoy PEP (Port 8000)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: apisix-gateway
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    # Allow SPIFFE / SPIRE attestation agent
    - fromEntities:
        - host
  egress:
    # Allow traffic within same tenant environment
    - toEndpoints:
        - matchLabels:
            darueira.io/tier: tenant-workload
    # Allow DNS resolution
    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # Allow communication to Central Shared Services (OpenBao, IdP, APM)
    - toEndpoints:
        - matchLabels:
            darueira.io/tier: enterprise-shared
