apiVersion: v1
kind: Secret
metadata:
  name: tenant-db-credentials
  labels:
    darueira.io/tier: tenant-workload
    app.kubernetes.io/component: relational-database
type: Opaque
stringData:
  database: "tenant_app_db"
  username: "tenant_db_user"
  password: "tenant_pg_secure_pass_2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-keycloak-credentials
  labels:
    darueira.io/tier: tenant-workload
    app.kubernetes.io/component: identity-provider
type: Opaque
stringData:
  admin-username: "drr_tenant_admin"
  admin-password: "tenant_keycloak_pass_2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-mongo-credentials
  labels:
    darueira.io/tier: tenant-workload
    app.kubernetes.io/component: nosql-database
type: Opaque
stringData:
  database: "tenant_doc_db"
  root-username: "tenant_mongo_admin"
  root-password: "tenant_mongo_secure_pass_2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-minio-credentials
  labels:
    darueira.io/tier: tenant-workload
    app.kubernetes.io/component: object-storage
type: Opaque
stringData:
  root-user: "drr_tenant_admin"
  root-password: "drr_tenant_s3_pass_2026"
