apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drr-corpshared-mgmt

resources:
  - namespace.yaml
  - network-policy.yaml
  - backstage.yaml
  - argocd-server.yaml
  - tekton-pipeline-engine.yaml
