apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-and-mgmt-rules
  namespace: drr-corpshared-mgmt
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            darueira.io/tier: enterprise-shared
      toPorts:
        - ports:
            - port: "7007"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "9090"
              protocol: TCP
    - fromEntities:
        - host
        - cluster
  egress:
    - toEndpoints:
        - matchLabels:
            darueira.io/tier: enterprise-shared
    - toEntities:
        - cluster
        - kube-apiserver
        - world
