apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: drr-corpshared-obs
  labels:
    app.kubernetes.io/name: opensearch
    darueira.io/tier: enterprise-shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opensearch
        darueira.io/tier: enterprise-shared
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.15.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: discovery.type
              value: single-node
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "Admin!123456_DevKey!"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            - name: bootstrap.memory_lock
              value: "false"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: drr-corpshared-obs
  labels:
    app.kubernetes.io/name: opensearch
    darueira.io/tier: enterprise-shared
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opensearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
