apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-ci-pipeline-run
  namespace: drr-corpshared-mgmt
  labels:
    tekton.dev/pipeline: standard-ci-cd-pipeline
    darueira.io/tenant: acme
    darueira.io/project: storefront
    darueira.io/environment: prod
spec:
  pipelineRef:
    name: standard-ci-cd-pipeline
  params:
    - name: git-url
      value: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/drr-admin/darueira-privatecloud-platform.git"
    - name: git-revision
      value: "master"
    - name: runtime
      value: "golang"
    - name: source-subpath
      value: "apps/drr-ctlr-cli"
    - name: image-name
      value: "nexus-oss.drr-corpshared-plat.svc.cluster.local:8082/darueira/drr-ctlr-cli:latest"
    - name: dockerfile-path
      value: "Dockerfile"
    - name: argocd-app-name
      value: "corpshared-mgmt"
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
