apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-market-06-service
  namespace: drr-tnt-swfabrik-europe-dev
  labels:
    app.kubernetes.io/name: food-market-06-service
    app.kubernetes.io/part-of: swfabrik-europe-marketplaces
    darueira.io/tier: tenant-workload
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: marketplaces
    darueira.io/env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: food-market-06-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: food-market-06-service
        app.kubernetes.io/part-of: swfabrik-europe-marketplaces
        darueira.io/tier: tenant-workload
        darueira.io/tenant: swfabrik-europe
        darueira.io/project: marketplaces
        darueira.io/env: dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: localhost:8082/swfabrik-europe/food-market-06-service:1.0.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8086
              name: http
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8086"
            - name: DATABASE_URL
              value: "postgres://drr_tnt_svcs_admin:tenant_pg_secure_pass_2026@tenant-postgres.drr-tnt-swfabrik-europe-dev.svc.cluster.local:5432/drr_tnt_bizapps_db?sslmode=disable"
            - name: RABBITMQ_HOST
              value: "message-broker-rabbitmq.drr-corpshared-plat.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "drr_admin"
            - name: RABBITMQ_PASS
              value: "darueira-admin123"
            - name: RABBITMQ_VHOST
              value: "/"
            - name: APP_MARKET_ID
              value: "MKT-EU-06-DOTNET"
            - name: APP_RABBITMQ_TOPIC
              value: "marketplace.foodtrading.topic"
            - name: APP_RABBITMQ_QUEUE
              value: "marketplace.foodtrading.queue06"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: food-market-06-service
  namespace: drr-tnt-swfabrik-europe-dev
  labels:
    app.kubernetes.io/name: food-market-06-service
    darueira.io/tier: tenant-workload
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: food-market-06-service
  ports:
    - port: 8086
      targetPort: 8086
      name: http
