quarkus.application.name=food-market-02-service
quarkus.http.port=8082
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Database Connection (Agroal JDBC)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://central-postgres.drr-corpshared-plat.svc.cluster.local:5432/drr_tnt_bizapps_db?currentSchema=schm02}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:drr_admin}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:change-me-in-openbao}

# RabbitMQ Configuration
rabbitmq-host=${RABBITMQ_HOST:message-broker-rabbitmq.drr-corpshared-plat.svc.cluster.local}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:drr_admin}
rabbitmq-password=${RABBITMQ_PASSWORD:darueira-admin123}
rabbitmq-virtual-host=${RABBITMQ_VHOST:/}

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# App settings
app.market-id=${APP_MARKET_ID:MKT-EU-02-QUARKUS}
app.rabbitmq.topic=${APP_RABBITMQ_TOPIC:marketplace.foodtrading.topic}
app.rabbitmq.queue=${APP_RABBITMQ_QUEUE:marketplace.foodtrading.queue01}
