apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-tenant-infra
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: infrastructure
    darueira.io/tier: tenant-infrastructure
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/infra-k8s.git"
    targetRevision: main
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-app-host-mfe
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: frontend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/app-food-market-00-mfe-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-app-react-01
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: frontend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/app-food-market-01-react-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-app-angular-02
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: frontend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/app-food-market-02-angular-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-food-market-01
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: backend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/food-market-01-service-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-food-market-02
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: backend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/food-market-02-service-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-food-market-03
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: backend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/food-market-03-service-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-food-market-04
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: backend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/food-market-04-service-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-food-market-05
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: backend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/food-market-05-service-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swfabrik-europe-food-market-06
  namespace: drr-corpshared-mgmt
  labels:
    darueira.io/tenant: swfabrik-europe
    darueira.io/project: backend
    darueira.io/tier: tenant-workload
spec:
  project: darueira-tenants
  source:
    repoURL: "http://forgejo-git.drr-corpshared-plat.svc.cluster.local:3000/swfabrik-europe/food-market-06-service-chart.git"
    targetRevision: main
    path: "."
    helm:
      valueFiles:
        - "values.yaml"
        - "values-dev-green.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "drr-tnt-swfabrik-europe-dev"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

