apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drr-corpshared-secr-internal

resources:
  - namespace.yaml
  - network-policy.yaml
  - openbao-master.yaml
  - spire-server.yaml
