apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server
  namespace: drr-corpshared-plat
  labels:
    app.kubernetes.io/name: keycloak
    darueira.io/tier: enterprise-shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        darueira.io/tier: enterprise-shared
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.7.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          args:
            - start-dev
            - --http-enabled=true
            - --http-port=8080
            - --health-enabled=true
            - --metrics-enabled=true
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: management
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin123-dev"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "central-postgres.drr-corpshared-plat.svc.cluster.local"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "drr_controlplane_db"
            - name: KC_DB_USERNAME
              value: "drr_admin"
            - name: KC_DB_PASSWORD
              value: "change-me-in-openbao"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: drr-corpshared-plat
  labels:
    app.kubernetes.io/name: keycloak
    darueira.io/tier: enterprise-shared
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 9000
      targetPort: 9000
      name: management
