apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
  namespace: drr-corpshared-plat
  labels:
    app.kubernetes.io/name: openfga
    app.kubernetes.io/component: rebac-engine
    darueira.io/tier: enterprise-shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openfga
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openfga
        darueira.io/tier: enterprise-shared
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: openfga
          image: openfga/openfga:v1.8.3
          imagePullPolicy: IfNotPresent
          args:
            - run
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: OPENFGA_LOG_FORMAT
              value: "json"
            - name: OPENFGA_DATASTORE_ENGINE
              value: "memory"
            - name: OPENFGA_PLAYGROUND_ENABLED
              value: "true"
            - name: OPENFGA_PLAYGROUND_PORT
              value: "3000"
            - name: OPENFGA_HTTP_ADDR
              value: "0.0.0.0:8080"
            - name: OPENFGA_GRPC_ADDR
              value: "0.0.0.0:8081"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: grpc
            - containerPort: 3000
              name: playground
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: openfga
  namespace: drr-corpshared-plat
  labels:
    app.kubernetes.io/name: openfga
    darueira.io/tier: enterprise-shared
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openfga
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8081
      targetPort: 8081
      name: grpc
    - port: 3000
      targetPort: 3000
      name: playground
